# -*- coding: utf-8 -*-
from Products.CMFCore.utils import getToolByName
from Products.CMFPlone.utils import _createObjectByType
from plone.app.controlpanel.mail import IMailSchema


def setupVarious(context):
    if context.readDataFile('notes.kbtic_various.txt') is None:
        return
    portal = context.getSite()

    # permetre @. als usernames
    portal.portal_registration.manage_editIDPattern('^[A-Za-z][A-Za-z0-9_\-@.]*$')

    # configurem mail
    mail = IMailSchema(portal)
    mail.smtp_host = u'localhost'
    mail.email_from_name = "Administrador Web"
    mail.email_from_address = "noreply@localhost.cat"

    # Paraules clau Serveis
    voctool = getToolByName(portal, 'portal_vocabularies')
    try:
        category1_keywords = _createObjectByType('SortedSimpleVocabulary', voctool, 'category1_keywords')
        keywords = [
                    (u"catServei-01", u"Actualització de continguts en el Web UPC"),
                    (u"catServei-02", u"ACUP - Doc6"),
                    (u"catServei-03", u"Address Book - PAB"),
                    (u"catServei-04", u"Adminpack"),
                    (u"catServei-05", u"Adquira"),
                    (u"catServei-06", u"Alumni UPC"),
                    (u"catServei-07", u"Antivirus"),
                    (u"catServei-08", u"ARI"),
                    (u"catServei-09", u"Atenció Immediata"),
                    (u"catServei-10", u"Atenció Usuaris"),
                    (u"catServei-11", u"Backups"),
                    (u"catServei-12", u"Bases de dades bibliogràfiques"),
                    (u"catServei-13", u"Bibliotècnica"),
                    (u"catServei-14", u"Blackberry Enterprise Server"),
                    (u"catServei-15", u"Campus Digital"),
                    (u"catServei-16", u"Campus Digital - Atenea Mobil"),
                    (u"catServei-17", u"Campus Digital - Atenea1x1"),
                    (u"catServei-18", u"Campus Digital - AteneaSaurus"),
                    (u"catServei-19", u"Campus Digital - Externs"),
                    (u"catServei-20", u"Campus Digital - Moodle"),
                    (u"catServei-21", u"Canal UPC TV"),
                    (u"catServei-22", u"Canvis de contrasenya"),
                    (u"catServei-23", u"Carnet UPC"),
                    (u"catServei-24", u"CAS - Central authentication service"),
                    (u"catServei-25", u"Catàleg de les biblioteques de la UPC"),
                    (u"catServei-26", u"CCE"),
                    (u"catServei-27", u"Cerca d'adreces de correu en webs vulnerables a l'spam"),
                    (u"catServei-28", u"Cercador UPC"),
                    (u"catServei-29", u"Certificats"),
                    (u"catServei-30", u"Clients Externs UPCnet"),
                    (u"catServei-31", u"Cloud privat upc"),
                    (u"catServei-32", u"CMSW"),
                    (u"catServei-33", u"Col·laboratoris"),
                    (u"catServei-34", u"Connexió Remota VNC"),
                    (u"catServei-35", u"Correu Electrònic"),
                    (u"catServei-36", u"Correu Electrònic - Domino"),
                    (u"catServei-37", u"Correu Electrònic - Nous Relays"),
                    (u"catServei-38", u"Correu Electrònic - PL"),
                    (u"catServei-39", u"Correu Electrònic - Relays"),
                    (u"catServei-40", u"CSPT"),
                    (u"catServei-41", u"Directori UPC"),
                    (u"catServei-42", u"Distribucio de Software"),
                    (u"catServei-43", u"DNS"),
                    (u"catServei-44", u"DOCUMENTUM"),
                    (u"catServei-45", u"Domini UPCXXI"),
                    (u"catServei-46", u"Domino"),
                    (u"catServei-47", u"Drac"),
                    (u"catServei-48", u"e-Desk Conferències web"),
                    (u"catServei-49", u"e-enquestes"),
                    (u"catServei-50", u"eAdministració"),
                    (u"catServei-51", u"Entitat de Registre"),
                    (u"catServei-52", u"Envío de mensajes vía SMS"),
                    (u"catServei-53", u"EPI"),
                    (u"catServei-54", u"etpl"),
                    (u"catServei-55", u"Evalwin"),
                    (u"catServei-56", u"FACIL"),
                    (u"catServei-57", u"FAMA"),
                    (u"catServei-58", u"FENIX"),
                    (u"catServei-59", u"Firewalls"),
                    (u"catServei-60", u"Gartner"),
                    (u"catServei-61", u"gAUSS"),
                    (u"catServei-62", u"gCFG"),
                    (u"catServei-63", u"gCON"),
                    (u"catServei-64", u"gCOT"),
                    (u"catServei-65", u"Generació de certificats especials"),
                    (u"catServei-66", u"GenGrups"),
                    (u"catServei-67", u"GenWeb"),
                    (u"catServei-68", u"Gestió d'eleccions"),
                    (u"catServei-69", u"Gestió de garanties"),
                    (u"catServei-70", u"Gestionados"),
                    (u"catServei-71", u"Gestor de serveis"),
                    (u"catServei-72", u"GRED"),
                    (u"catServei-73", u"GRED-UNED"),
                    (u"catServei-74", u"gSMS"),
                    (u"catServei-75", u"Hosting"),
                    (u"catServei-76", u"Hosting Web"),
                    (u"catServei-77", u"HR-Access"),
                    (u"catServei-78", u"Identitat Digital"),
                    (u"catServei-79", u"IdP UPC"),
                    (u"catServei-80", u"Intranet"),
                    (u"catServei-81", u"Intranet UPCnet"),
                    (u"catServei-82", u"K2 estudiants"),
                    (u"catServei-83", u"K2 externs"),
                    (u"catServei-84", u"K2 UPCnet"),
                    (u"catServei-85", u"KATA"),
                    (u"catServei-86", u"LDAP"),
                    (u"catServei-87", u"LDAP UPC"),
                    (u"catServei-88", u"LDAP: OpenLdap"),
                    (u"catServei-89", u"Liceu"),
                    (u"catServei-90", u"Linux"),
                    (u"catServei-91", u"Majordomo"),
                    (u"catServei-92", u"Manteniment"),
                    (u"catServei-93", u"Matricula"),
                    (u"catServei-94", u"MATUPC"),
                    (u"catServei-95", u"monCCD"),
                    (u"catServei-96", u"Monitorització"),
                    (u"catServei-97", u"Monitorización"),
                    (u"catServei-98", u"Mysql"),
                    (u"catServei-99", u"Navision"),
                    (u"catServei-100", u"Notes"),
                    (u"catServei-101", u"OBSOLET"),
                    (u"catServei-102", u"Pàgines web personals"),
                    (u"catServei-103", u"Pidgin"),
                    (u"catServei-104", u"PLONE"),
                    (u"catServei-105", u"Practicum"),
                    (u"catServei-106", u"Presencia"),
                    (u"catServei-107", u"Prisma"),
                    (u"catServei-108", u"Prisma Renove"),
                    (u"catServei-109", u"Progeny"),
                    (u"catServei-110", u"Projecte Davyd - Sala Juntes Master's"),
                    (u"catServei-111", u"Proxy"),
                    (u"catServei-112", u"Redes administradas por UPCnet"),
                    (u"catServei-113", u"Reparacions i Petites Ampliacions de Cablat"),
                    (u"catServei-114", u"Repositori PL UPCnet"),
                    (u"catServei-115", u"Resolució d'incidències"),
                    (u"catServei-116", u"Reus Educat"),
                    (u"catServei-117", u"Revisat"),
                    (u"catServei-118", u"Revisions Mèdiques"),
                    (u"catServei-119", u"SAI: Servei d'Accés a Internet"),
                    (u"catServei-120", u"SAP"),
                    (u"catServei-121", u"Seguretat"),
                    (u"catServei-122", u"Servei de Correcció Òptica d'Exàmens de l'ICE"),
                    (u"catServei-123", u"Servidor TV per a la UPC"),
                    (u"catServei-124", u"Servidors"),
                    (u"catServei-125", u"SIGMA"),
                    (u"catServei-126", u"SIrena"),
                    (u"catServei-127", u"Spa"),
                    (u"catServei-128", u"SQLserver"),
                    (u"catServei-129", u"SSL"),
                    (u"catServei-130", u"Suport de 2n nivell"),
                    (u"catServei-131", u"Suport Tecnic Especialitzat"),
                    (u"catServei-132", u"Sympa"),
                    (u"catServei-133", u"Tarifes-Costos Directes"),
                    (u"catServei-134", u"Tarifes-Simulador de costos"),
                    (u"catServei-135", u"Telefonia"),
                    (u"catServei-136", u"Teletreball"),
                    (u"catServei-137", u"Televot"),
                    (u"catServei-138", u"TOF"),
                    (u"catServei-139", u"TOTQ"),
                    (u"catServei-140", u"Traveler"),
                    (u"catServei-141", u"Ts"),
                    (u"catServei-142", u"Ubuntu"),
                    (u"catServei-143", u"UPCconnect"),
                    (u"catServei-144", u"UPClink"),
                    (u"catServei-145", u"videoconferencia"),
                    (u"catServei-146", u"Web UPC"),
                    (u"catServei-147", u"Web UPCnet"),
                    (u"catServei-148", u"webDAV - Accés a repositoris de fitxers (UPC/UPCnet) via web"),
                    (u"catServei-149", u"Web_Edicions"),
                    (u"catServei-150", u"Xarxa"),
                    (u"catServei-151", u"Xarxa Troncal"),
                    (u"catServei-152", u"XSF"),
                    (u"catServei-153", u"XSF DIBA"),
                    (u"catServei-154", u"Z - Informació obsoleta"),
                     ]
        for keyword in keywords:
            object = _createObjectByType('SimpleVocabularyTerm', category1_keywords, keyword[0])
            object.setTitle(keyword[1])
            object.reindexObject()
    except:
        pass

    #paraules clau Serveu PPS
    try:
        category2_keywords = _createObjectByType('SortedSimpleVocabulary', voctool, 'category2_keywords')
        keywords = [
 (u"catServeiPPS-01", u"gSMS - Gestió d'enviament d'SMS"),
                    (u"catServeiPPS-02", u"10100-00 Atenció a  l'usuari"),
                    (u"catServeiPPS-03", u"10101-00 Correcció exàmens ICE"),
                    (u"catServeiPPS-04", u"10200-00 Resolució de consultes ofimàtiques"),
                    (u"catServeiPPS-05", u"10300-00 Correu electrònic"),
                    (u"catServeiPPS-06", u"10301-00 Correu electrònic DN"),
                    (u"catServeiPPS-07", u"10302-00 Correu electrònic K2"),
                    (u"catServeiPPS-08", u"10303-00 Relay i gestió de dominis de correu"),
                    (u"catServeiPPS-09", u"10304-00 Llistes de distribució de correu"),
                    (u"catServeiPPS-10", u"10312-00 Agenda K2"),
                    (u"catServeiPPS-11", u"10350-00 Missatgeria instantània"),
                    (u"catServeiPPS-12", u"10400-00 Impressió en xarxa"),
                    (u"catServeiPPS-13", u"10500-00 Repositori de fitxers"),
                    (u"catServeiPPS-14", u"10501-00 Repositori de fitxers personals"),
                    (u"catServeiPPS-15", u"10502-00 Repositori de fitxers de grup"),
                    (u"catServeiPPS-16", u"10600-00 Gestió d'estacions de treball personals"),
                    (u"catServeiPPS-17", u"10610-00 Configuració mantinguda de software"),
                    (u"catServeiPPS-18", u"10611-00 Configuració mantinguda de software - entorn Windows"),
                    (u"catServeiPPS-19", u"10612-00 Configuració mantinguda de software - entorn Linux"),
                    (u"catServeiPPS-20", u"10612-01 Configuració PUB-Linux (SBD)"),
                    (u"catServeiPPS-21", u"10620-00 Instal·lació de software"),
                    (u"catServeiPPS-22", u"10800-00 Xarxa sense fils (XSF)"),
                    (u"catServeiPPS-23", u"10900-00 Dispositius mòbils"),
                    (u"catServeiPPS-24", u"10910-00 Blackberry DN"),
                    (u"catServeiPPS-25", u"11000-00 Bases de dades bibliogràfiques en CD-ROM"),
                    (u"catServeiPPS-26", u"11100-00 Hosting de pàgines web personals"),
                    (u"catServeiPPS-27", u"12100-00 Suport tècnic especialitzat"),
                    (u"catServeiPPS-28", u"12110-00 Assessorament a PAS TIC de la UPC"),
                    (u"catServeiPPS-29", u"12110-00 Suport de 2n nivell"),
                    (u"catServeiPPS-30", u"14000-00 Portal de serveis a l'usuari"),
                    (u"catServeiPPS-31", u"20100-00 Subministraments"),
                    (u"catServeiPPS-32", u"20104-00 Subministrament d'equips de telefonia fixa"),
                    (u"catServeiPPS-33", u"20108-00 Adquisició de llicències de software"),
                    (u"catServeiPPS-34", u"20200-00 Manteniment"),
                    (u"catServeiPPS-35", u"20201-00 Manteniment de llicències de software base de servidors"),
                    (u"catServeiPPS-36", u"20206-00 Manteniment hardware d'equips ofimàtics"),
                    (u"catServeiPPS-37", u"20207-00 Manteniment hardware d'equips electrònics de comunicacions de dades"),
                    (u"catServeiPPS-38", u"20208-00 Manteniment hardware de servidors"),
                    (u"catServeiPPS-39", u"20300-00 Telefonia mòbil"),
                    (u"catServeiPPS-40", u"20304-00 gSMS - Gestió d'enviament d'SMS"),
                    (u"catServeiPPS-41", u"20400-00 Distribució de software"),
                    (u"catServeiPPS-42", u"20401-00 Distribució de llicències de software i control de llicències flotants"),
                    (u"catServeiPPS-43", u"20500-00 Gestió de garanties"),
                    (u"catServeiPPS-44", u"20600-00 KATA: portal de compres TIC"),
                    (u"catServeiPPS-45", u"30100-00 Directori / Intranet"),
                    (u"catServeiPPS-46", u"30101-00 Directori"),
                    (u"catServeiPPS-47", u"30102-00 Identificació a la Intranet"),
                    (u"catServeiPPS-48", u"30103-00 Autenticació Directori LDAP"),
                    (u"catServeiPPS-49", u"30104-00 gAUSS - gestió de l'Autenticació d'USuaris i Serveis"),
                    (u"catServeiPPS-50", u"30104-00 gAUSS - gestió de la Autenticació d'USuaris i Serveis"),
                    (u"catServeiPPS-51", u"30110-00"),
                    (u"catServeiPPS-52", u"30110-00 Certificació Carnet UPC"),
                    (u"catServeiPPS-53", u"30200-00 Campus Digitals i col·laboratoris per a la docència"),
                    (u"catServeiPPS-54", u"30300-00 Gestió econòmica"),
                    (u"catServeiPPS-55", u"30400-00 Gestió de personal"),
                    (u"catServeiPPS-56", u"30500-00 Petits ERP"),
                    (u"catServeiPPS-57", u"30501-00 gRED - Gestió del registre d'entrada i sortida de documents"),
                    (u"catServeiPPS-58", u"30503-00 Gestió de relacions institucionals i internacionals"),
                    (u"catServeiPPS-59", u"30504-00 gCOT - Gestió de Consums de Telefonia"),
                    (u"catServeiPPS-60", u"30600-00 Gestió de la docència"),
                    (u"catServeiPPS-61", u"30600-00 Gestió de la docència i la recerca"),
                    (u"catServeiPPS-62", u"30610-00 Gestió de la matriculació de primer i segon cicle"),
                    (u"catServeiPPS-63", u"30612-00 Gestió de titulacions"),
                    (u"catServeiPPS-64", u"30613-00 Gestió del doctorat"),
                    (u"catServeiPPS-65", u"30640-00 Gestió de l'Associació d'Amics de la UPC"),
                    (u"catServeiPPS-66", u"30800-00 Gestió de biblioteques"),
                    (u"catServeiPPS-67", u"39000-00 Gestió de les enquestes de professors"),
                    (u"catServeiPPS-68", u"40100-00 Sistemes d'Informació d'UPCnet"),
                    (u"catServeiPPS-69", u"40102-00 Gestió de l'atenció a l'usuari (ATIC)"),
                    (u"catServeiPPS-70", u"40102-00 Gestor de Serveis"),
                    (u"catServeiPPS-71", u"40104-00 Intranet d'UPCnet"),
                    (u"catServeiPPS-72", u"40200-00 Allotjament de webs i col·laboratoris"),
                    (u"catServeiPPS-73", u"40200-00 Hosting de col·laboratoris"),
                    (u"catServeiPPS-74", u"40201-00 Allotjament de webs i col·laboratoris sobre Linux"),
                    (u"catServeiPPS-75", u"40202-00 Allotjament de webs i col·laboratoris sobre Lotus Domino"),
                    (u"catServeiPPS-76", u"40202-01 Allotjament de Web i Col·laboratoris en tecnologia Lotus Domino - Família"),
                    (u"catServeiPPS-77", u"40204-00 Allotjament de Web i Col·laboratoris al domini www.upc.edu"),
                    (u"catServeiPPS-78", u"40204-00 Web corporativa de la UPC"),
                    (u"catServeiPPS-79", u"40300-00 Sistemes de gestió de continguts web"),
                    (u"catServeiPPS-80", u"40301-00 Eines de gestió de Web i Col·laboratoris basats en Plone"),
                    (u"catServeiPPS-81", u"40301-00 GenWeb UPC"),
                    (u"catServeiPPS-82", u"50102-00 Instal·lació de software base de servidors"),
                    (u"catServeiPPS-83", u"50111-00 Hosting de servidors"),
                    (u"catServeiPPS-84", u"50111-00 Hosting dedicat de servidors"),
                    (u"catServeiPPS-85", u"50113-00 Hosting d'aplicacions"),
                    (u"catServeiPPS-86", u"50121-00 Hosting compartit i  webs"),
                    (u"catServeiPPS-87", u"50121-00 Hosting de webs"),
                    (u"catServeiPPS-88", u"50122-00 Allotjament i administració de webs"),
                    (u"catServeiPPS-89", u"50123-00 Hosting compartit de BBDD"),
                    (u"catServeiPPS-90", u"50124-00 Hosting Prisma"),
                    (u"catServeiPPS-91", u"50201-00 Monitorització de servidors"),
                    (u"catServeiPPS-92", u"50202-00 Còpies de seguretat de dades de servidors no gestionats per UPCnet"),
                    (u"catServeiPPS-93", u"50301-00 Gestió de dominis d'Internet (DNS)"),
                    (u"catServeiPPS-94", u"50403-00 Telefonia fixa"),
                    (u"catServeiPPS-95", u"50404-00 Telefonia fixa IP"),
                    (u"catServeiPPS-96", u"50501-00 Instal·lació d'equips electrònics de comunicacions de dades"),
                    (u"catServeiPPS-97", u"50502-00 Instal·lació de punts de xarxa"),
                    (u"catServeiPPS-98", u"50503-00 Manteniment del cablat de xarxa"),
                    (u"catServeiPPS-99", u"50504-00 Administració de xarxes locals"),
                    (u"catServeiPPS-100", u"50504-00 Administració i connexió de xarxes locals"),
                    (u"catServeiPPS-101", u"50505-00 Reparacions i petites ampliacions de cablat"),
                    (u"catServeiPPS-102", u"50551-00 Administració de la xarxa troncal i la connexió a Internet"),
                    (u"catServeiPPS-103", u"50601-00 Accés remot als recursos informàtics de la UPC i a Internet"),
                    (u"catServeiPPS-104", u"50602-00 Accés remot a Internet"),
                    (u"catServeiPPS-105", u"50602-00 Accés remot a Internet (accés ""UPCnet"")"),
                    (u"catServeiPPS-106", u"50604-00 Accés remot a Internet (antic accés UPCnet)"),
                    (u"catServeiPPS-107", u"50801-00 Tallafocs de Campus gestionats"),
                    (u"catServeiPPS-108", u"50802-00 Tallafocs Externs gestionats"),
                    (u"catServeiPPS-109", u"50900-00 Xarxa Sense Fils (XSF)"),
                    (u"catServeiPPS-110", u"60101-00 Adaptació ergonòmica i de la usabilitat d’aplicatius"),
                    (u"catServeiPPS-111", u"60102-00 Assessoria i consultoria en disseny"),
                    (u"catServeiPPS-112", u"60105-00 Creació de Programes d’imatge corporativa"),
                    (u"catServeiPPS-113", u"60200-00 reus eduCAT"),
                    (u"catServeiPPS-114", u"70000-00 Assessorament general sobre les TIC"),
                    (u"catServeiPPS-115", u"80000-00 Altres productes"),
                    (u"catServeiPPS-116", u"80100-00 Genèric (global a varis productes)"),
                    (u"catServeiPPS-117", u"90000-00 Sense Servei"),
                    (u"catServeiPPS-118", u"Directiva organizativa: %s|(No se ha asignado ninguna directiva explícita)|(No  se"),
                    (u"catServeiPPS-119", u"(Not Categorized)"),
                       ]
        for keyword in keywords:
            object = _createObjectByType('SimpleVocabularyTerm', category2_keywords, keyword[0])
            object.setTitle(keyword[1])
            object.reindexObject()
    except:
        pass

    portal.setTitle("Portal Notes")

    langtool = getToolByName(portal, 'portal_languages')
    langtool.manage_setLanguageSettings(defaultLanguage='ca',
                                        supportedLanguages=['ca'],
                                        setUseCombinedLanguageCodes=0,
                                        setForcelanguageUrls=0,
                                        setPathN=1,
                                        setCookieN=1,
                                        setAllowContentLanguageFallback=0,
                                        setRequestN=0,
                                        startNeutral=1,
                                        displayFlags=False)
